### ISSUE TITLE
Packaging: Updated RPM for Cygwin

### ISSUE THREAD

**Issue by bradjc** [tinyos/nesc#17]
The http://docs.tinyos.net/tinywiki/index.php/Manual_installation_using_RPM_packages wiki page has an outdated version of nescc for Cygwin. However, something has changed and TinyOS needs a newer version of nescc. Can this be updated?

Also, I have the RPM (thanks to the nice script in tinyos-main/packaging) if that would be useful.

**Comment by cire831** [comment]
ancient at this point

not going to happen
