### ISSUE TITLE
Where would one go to discuss nesc code?

### ISSUE THREAD

**Issue by sstewartgallus** [tinyos/nesc#37]
I am trying out nesc (and not using tinyos itself, I'm using Linux) for a small executable inside of a personal project because it handles both asynchronous behaviour and manual memory management well. I would like to ask some for code review and advice on nesc. However, there does not seem to be anywhere online that seem appropriate for this kind of discussion. Should I just go to the tinyos mailing list? Is there anywhere else more appropriate? Should a mailing list for users of nesc be created or are the existing mailing lists good enough for the small community? There also seems to be an old site for nesc at http://nescc.sourceforge.net/ but that seems out of date to me. Maybe the contents of that page should be moved over to the main site?

**Comment by cire831** [comment]
On Wed, Dec 23, 2015 at 1:22 PM, Steven Stewart-Gallus <
notifications@github.com> wrote:

> I am trying out nesc (and not using tinyos itself, I'm using Linux) for a
> small executable inside of a personal project because it handles both
> asynchronous behaviour and manual memory management well. I would like to
> ask some for code review and advice on nesc. However, there does not seem
> to be anywhere online that seem appropriate for this kind of discussion.
> Should I just go to the tinyos mailing list?
>
I'd be happy to take a look.

sending to the tinyos-help list is fine.

there isn't another list.


> Is there anywhere else more appropriate? Should a maIiling list for users
> of nesc be created or are the existing mailing lists good enough for the
> small community? There also seems to be an old site for nesc at
> http://nescc.sourceforge.net/ but that seems out of date to me. Maybe the
> contents of that page should be moved over to the main site?
>

the source forge page is really old.  I don't know who owns it.  The github
page is the new master page.


Not sure what else needs to move over.

—
>


> Reply to this email directly or view it on GitHub
> <https://github.com/tinyos/nesc/issues/37>.
>



-- 
Eric B. Decker
Senior (over 50 :-) Researcher
