### ISSUE TITLE
Cannot make tinyos-tools

### ISSUE THREAD

**Issue by viquiram** [tinyos/nesc#48]
Here is the console's output:

`make  all-recursive
make[1]: Entering directory '/home/ecee/tinyos-main/tools'
Making all in platforms
make[2]: Entering directory '/home/ecee/tinyos-main/tools/platforms'
Making all in mica
make[3]: Entering directory '/home/ecee/tinyos-main/tools/platforms/mica'
Making all in cc1000-channelgen
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/mica/cc1000-channelgen'
depbase=`echo tos-channelgen.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../../..     -g -O2 -MT tos-channelgen.o -MD -MP -MF $depbase.Tpo -c -o tos-channelgen.o tos-channelgen.c &&\
mv -f $depbase.Tpo $depbase.Po
tos-channelgen.c: In function ‘main’:
tos-channelgen.c:308:17: warning: implicit declaration of function ‘atoi’ [-Wimplicit-function-declaration]
   DesiredFreq = atoi(argv[0]);
                 ^~~~
gcc  -g -O2   -o tos-channelgen tos-channelgen.o  
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/mica/cc1000-channelgen'
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/mica'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/mica'
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/mica'
Making all in msp430
make[3]: Entering directory '/home/ecee/tinyos-main/tools/platforms/msp430'
Making all in motelist
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/msp430/motelist'
cp motelist-linux motelist
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/msp430/motelist'
Making all in pybsl
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/msp430/pybsl'
Making all in serial
make[5]: Entering directory '/home/ecee/tinyos-main/tools/platforms/msp430/pybsl/serial'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/msp430/pybsl/serial'
make[5]: Entering directory '/home/ecee/tinyos-main/tools/platforms/msp430/pybsl'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/msp430/pybsl'
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/msp430/pybsl'
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/msp430'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/msp430'
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/msp430'
Making all in sam3
make[3]: Entering directory '/home/ecee/tinyos-main/tools/platforms/sam3'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/sam3'
Making all in ucmote
make[3]: Entering directory '/home/ecee/tinyos-main/tools/platforms/ucmote'
Making all in motelist2
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/ucmote/motelist2'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/ucmote/motelist2'
Making all in mcp2200gpio
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/ucmote/mcp2200gpio'
gcc mcp2200gpio.c -O2 -o mcp2200gpio
mcp2200gpio.c: In function ‘main’:
mcp2200gpio.c:144:6: warning: implicit declaration of function ‘close’; did you mean ‘pclose’? [-Wimplicit-function-declaration]
      close(fd);
      ^~~~~
      pclose
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/ucmote/mcp2200gpio'
make[4]: Entering directory '/home/ecee/tinyos-main/tools/platforms/ucmote'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/ucmote'
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/platforms/ucmote'
make[3]: Entering directory '/home/ecee/tinyos-main/tools/platforms'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/platforms'
make[2]: Leaving directory '/home/ecee/tinyos-main/tools/platforms'
Making all in tinyos
make[2]: Entering directory '/home/ecee/tinyos-main/tools/tinyos'
Making all in cpp
make[3]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/cpp'
Making all in sf
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/cpp/sf'
g++ -DHAVE_CONFIG_H -I. -I../../..  -Wall -O3 -pthread   -g -O2 -MT sf2-basecomm.o -MD -MP -MF .deps/sf2-basecomm.Tpo -c -o sf2-basecomm.o `test -f 'basecomm.cpp' || echo './'`basecomm.cpp
mv -f .deps/sf2-basecomm.Tpo .deps/sf2-basecomm.Po
g++ -DHAVE_CONFIG_H -I. -I../../..  -Wall -O3 -pthread   -g -O2 -MT sf2-packetbuffer.o -MD -MP -MF .deps/sf2-packetbuffer.Tpo -c -o sf2-packetbuffer.o `test -f 'packetbuffer.cpp' || echo './'`packetbuffer.cpp
mv -f .deps/sf2-packetbuffer.Tpo .deps/sf2-packetbuffer.Po
g++ -DHAVE_CONFIG_H -I. -I../../..  -Wall -O3 -pthread   -g -O2 -MT sf2-serialcomm.o -MD -MP -MF .deps/sf2-serialcomm.Tpo -c -o sf2-serialcomm.o `test -f 'serialcomm.cpp' || echo './'`serialcomm.cpp
mv -f .deps/sf2-serialcomm.Tpo .deps/sf2-serialcomm.Po
g++ -DHAVE_CONFIG_H -I. -I../../..  -Wall -O3 -pthread   -g -O2 -MT sf2-sfcontrol.o -MD -MP -MF .deps/sf2-sfcontrol.Tpo -c -o sf2-sfcontrol.o `test -f 'sfcontrol.cpp' || echo './'`sfcontrol.cpp
mv -f .deps/sf2-sfcontrol.Tpo .deps/sf2-sfcontrol.Po
g++ -DHAVE_CONFIG_H -I. -I../../..  -Wall -O3 -pthread   -g -O2 -MT sf2-sf.o -MD -MP -MF .deps/sf2-sf.Tpo -c -o sf2-sf.o `test -f 'sf.cpp' || echo './'`sf.cpp
mv -f .deps/sf2-sf.Tpo .deps/sf2-sf.Po
g++ -DHAVE_CONFIG_H -I. -I../../..  -Wall -O3 -pthread   -g -O2 -MT sf2-sfpacket.o -MD -MP -MF .deps/sf2-sfpacket.Tpo -c -o sf2-sfpacket.o `test -f 'sfpacket.cpp' || echo './'`sfpacket.cpp
mv -f .deps/sf2-sfpacket.Tpo .deps/sf2-sfpacket.Po
g++ -DHAVE_CONFIG_H -I. -I../../..  -Wall -O3 -pthread   -g -O2 -MT sf2-tcpcomm.o -MD -MP -MF .deps/sf2-tcpcomm.Tpo -c -o sf2-tcpcomm.o `test -f 'tcpcomm.cpp' || echo './'`tcpcomm.cpp
mv -f .deps/sf2-tcpcomm.Tpo .deps/sf2-tcpcomm.Po
g++  -g -O2 -pthread  -o sf2 sf2-basecomm.o sf2-packetbuffer.o sf2-serialcomm.o sf2-sfcontrol.o sf2-sf.o sf2-sfpacket.o sf2-tcpcomm.o  
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/cpp/sf'
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/cpp'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/cpp'
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/cpp'
Making all in jni
make[3]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/jni'
Making all in env
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/jni/env'
gcc "-I/usr/lib/jvm/java-11-openjdk-amd64/include" -s -O2 "-I/usr/lib/jvm/java-11-openjdk-amd64/include/linux" -shared -fpic net_tinyos_util_Env.c -o libgetenv.so
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/jni/env'
Making all in serial
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/jni/serial'
g++ "-I/usr/lib/jvm/java-11-openjdk-amd64/include" -O2 -s "-I/usr/lib/jvm/java-11-openjdk-amd64/include/linux" -shared -fPIC NativeSerial_linux.cpp -o libtoscomm.so
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/jni/serial'
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/jni'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/jni'
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/jni'
Making all in misc
make[3]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/misc'
depbase=`echo tos-serial-debug.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT tos-serial-debug.o -MD -MP -MF $depbase.Tpo -c -o tos-serial-debug.o tos-serial-debug.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc  -g -O2   -o tos-serial-debug tos-serial-debug.o  
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/misc'
Making all in ncc
make[3]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/ncc'
Making all in nesdoc-py
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/ncc/nesdoc-py'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/ncc/nesdoc-py'
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/ncc'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/ncc'
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/ncc'
Making all in safe
make[3]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/safe'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/safe'
Making all in python
make[3]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/python'
Making all in message
make[4]: Entering directory '/home/ecee/tinyos-main/tools/tinyos/python/message'
nescc-mig -o SerialPacket.py -python-classname=SerialPacket python ../../../../tos/lib/serial/Serial.h serial_packet -I../../../../tos/lib/serial -I../../../../tos/types
nesC: Internal error.
Please submit an issue to the GitHub repository at https://github.com/tinyos/nesc
failed to parse message file ../../../../tos/lib/serial/Serial.h
Makefile:544: recipe for target 'SerialPacket.py' failed
make[4]: *** [SerialPacket.py] Error 1
make[4]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/python/message'
Makefile:499: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos/python'
Makefile:364: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ecee/tinyos-main/tools/tinyos'
Makefile:426: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ecee/tinyos-main/tools'
Makefile:359: recipe for target 'all' failed
make: *** [all] Error 2
`

Any ideas to solve the errors? BTW, I'm working with Ubuntu 18.04

**Comment by cire831** [comment]
that is unreadable.

please paste the output into a gist ```(https://gist.github.com/```) and resubmit.

also include what you used to invoke the build.

thanks.
