### ISSUE TITLE
Request Update of Ubuntu apt sources list.

### ISSUE THREAD

**Issue by ytlw** [tinyos/nesc#52]
The default `nescc` version in Ubuntu 18.04 is also 1.3.5, which will arise a `nesC Internal error` if we install `nescc` by `apt install nescc`.
It would work if we installed tinyos suite by the method in http://tinyprod.net/repos/debian,
but there is an installation issue in https://github.com/tinyos/tinyos-main/issues/429.

**Comment by cire831** [comment]
I've written a bug report for ubuntu 19.04 to point them at the right place for 1.3.6.

I've updated the tinyprod debian repository so it is using a modern signing key.  This issue is closed via tinyos/tinyos-main#429
